/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../components/common/AppLogo.vue')['default']
    IRiArrowLeftSLine: typeof import('~icons/ri/arrow-left-s-line')['default']
    IRiArrowRightSLine: typeof import('~icons/ri/arrow-right-s-line')['default']
    IRiCheckboxBlankLine: typeof import('~icons/ri/checkbox-blank-line')['default']
    IRiCheckboxMultipleBlankLine: typeof import('~icons/ri/checkbox-multiple-blank-line')['default']
    IRiCloseLine: typeof import('~icons/ri/close-line')['default']
    IRiHammerLine: typeof import('~icons/ri/hammer-line')['default']
    IRiMoonClearLine: typeof import('~icons/ri/moon-clear-line')['default']
    IRiMusic2Line: typeof import('~icons/ri/music2-line')['default']
    IRiPauseFill: typeof import('~icons/ri/pause-fill')['default']
    IRiPlayFill: typeof import('~icons/ri/play-fill')['default']
    IRiPlayListLine: typeof import('~icons/ri/play-list-line')['default']
    IRiSearchLine: typeof import('~icons/ri/search-line')['default']
    IRiSettings3Line: typeof import('~icons/ri/settings3-line')['default']
    IRiSkipBackFill: typeof import('~icons/ri/skip-back-fill')['default']
    IRiSkipForwardFill: typeof import('~icons/ri/skip-forward-fill')['default']
    IRiSubtractLine: typeof import('~icons/ri/subtract-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IRiVolumeUpLine: typeof import('~icons/ri/volume-up-line')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NResult: typeof import('naive-ui')['NResult']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSlider: typeof import('naive-ui')['NSlider']
    NTag: typeof import('naive-ui')['NTag']
    PlayerBar: typeof import('./../components/layout/PlayerBar.vue')['default']
    PlaylistCard: typeof import('./../components/common/PlaylistCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../components/layout/SideMenu.vue')['default']
    TitleBar: typeof import('./../components/layout/TitleBar.vue')['default']
    WindowControls: typeof import('./../components/layout/WindowControls.vue')['default']
  }
}
